config/routes.rb
Rails.application.routes.draw do
  root "club#home"

  get 'members/index'
  get 'members/new'
  get 'members/edit'
  get 'members/show'
  get 'members/create'
  get 'members/update'
  get 'members/destroy'

  get 'club/home'
  get 'club/about'
  get 'club/contact'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/application_controller_old.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @members = Member.all
  end

  def new
  end

  def edit
  end

  def show
    @member = Member.find(params[:id])
  end

  def create
  end

  def update
  end

  def destroy
  end

  private
    def member_params
      params.require(:member).permit(:name, :first_name, :licence_nb, :email, :facebook)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/club/_footer.html.erb
<div id="footer">

	<div class="footer1">
		<div class="element1 white bold">
			<%= image_tag("logoUSVofficiel.png", size: "40x40", alt: "Cat for President!") %>
		</div>

		<div class="element1 white bold">
			<p>US Villejuif TAA</p>
			<!-- logo officiel uniquement -->
		</div>

		<div class="element1 white bold">
			<p><%= link_to 'Contact', club_contact_path %></p>
		</div>

		<div class="element1 white bold">
			<p><%= link_to 'A propos', club_about_path %></p>
		</div>
	</div>

	<div class="footer2">
			<div class="element1 white bold">
				<p>Site en cours de réalisation par Isabelle Lechat</p>
			</div>

		<div class="element1 white bold">
			<%= image_tag("gummitch-space-r.jpg", size: "40x40", alt: "Cat for President!") %>
			<!-- retrouver gummitch (carte de visite) -->
		</div>
	</div>

</div>

app/views/club/_header.html.erb
<div id="header">

	<div class="element1 white bold">
		<%= image_tag("logo USV.png", size: "100x100", alt: "Cat for President!") %>
	</div>

	<div class="header1">
		<div class="element1 white bold">
			<p id="title-logo">US Villejuif Tir à l'Arc</p>
			<!-- logos -->
		</div>

		<div class="element1 white bold">
			<p><%= link_to "S'inscrire", members_new_path %></p> <!-- à remplacer par new_member_registration_path quand ça sera fait -->
		</div>

		<div class="element1 white bold">
			<p><%= link_to 'Se connecter', members_show_path %></p> <!-- à remplacer par new_member_session_path quand ça sera fait -->
		</div>
	</div>

	<div class="element1 white bold">
		<%= image_tag("logoUSVofficiel.png", size: "80x80", alt: "Cat for President!") %>
	</div>

</div>

app/views/club/about.html.erb
<%= render 'header' %>

<div id="main">
		<h1>A propos de l'US Villejuif</h1>
		<p class="bold">Historique</p>
		<p>Créé en 1980 par un petit groupe d'archers, </p>
		<p class="bold">Gymnase</p>
		<p>Ecole Robespierre</p>
		<p class="bold">Terrain extérieur</p>
		<p>Pas de tir Serge Barrois</p>
</div>

<%= render 'footer' %>

app/views/club/contact.html.erb
<%= render 'header' %>

<div id="main">
	<h1>Club#contact</h1>
	<p>Find me in app/views/club/contact.html.erb</p>
</div>
<%= render 'footer' %>

app/views/club/home.html.erb
<%= render 'header' %>

<div id="image-titre">
	<%= image_tag "photo_group_dept94.png", style: 'height:100%; width:100%' %>
</div>

<div id="carrousel">
	CARROUSEL
</div>

<div class="conteneur">
	<div class="ss-conteneur-p padding1">
		<h1>Où nous trouver ?</h1>
		<p class="bold">Gymnase</p>
		<p>Ecole Robespierre</p>
		<p class="bold">Terrain extérieur</p>
		<p>Pas de tir Serge Barrois</p>
	</div>

	<div class="ss-conteneur-i bg-lightlime">
		<%= image_tag " ", style: 'height:100%;width:100%;' %>
	</div>
</div>

<div class="conteneur">
	<div class="ss-conteneur-i bg-blue1">
		<%= image_tag " " %><%= image_tag " " %>
	</div>

	<div class="ss-conteneur-p padding1">
		<h1>Infos</h1>
		<p class="bold">cccc</p>
		<p>cccccccc</p>
	</div>
</div>

<div class="conteneur">
	<div class="ss-conteneur-p padding1">
		<h1>Compétitions</h1>
		<p class="bold">cccccc</p>
		<p>sssssss</p>
	</div>

	<div class="ss-conteneur-i bg-blue2">
		<%= image_tag " ", style: 'height:100%;width:100%;' %>
	</div>
</div>

<div class="conteneur">
	<div class="ss-conteneur-i bg-lime">
		<%= image_tag " " %><%= image_tag " " %>
	</div>

	<div class="ss-conteneur-p padding1">
		<h1>Classement</h1>
		<p class="bold">cccc</p>
		<p>cccccccc</p>
	</div>
</div>

<div class="conteneur">
	<div class="ss-conteneur-p padding1">
		<h1>Plumes et flèches de progression</h1>
		<p class="bold">cccccc</p>
		<p>sssssss</p>
	</div>

	<div class="ss-conteneur-i bg-blue1">
		<%= image_tag " " %><%= image_tag " " %>
	</div>
</div>

<div class="conteneur">
	<div class="ss-conteneur-i bg-yellow">
		<%= image_tag " ", style: 'height:100%;width:100%;' %>
	</div>

	<div class="ss-conteneur-p padding1">
		<h1>Evénements et travaux</h1>
		<p class="bold">Evénements</p>
		<p>sssssss</p>
		<p class="bold">Travaux au Terrain</p>
		<p>sssssss</p>
		<p class="bold">Travaux au Gymnase</p>
		<p>sssssss</p>
	</div>
</div>

<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UsvArc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/create.html.erb
<h1>Members#create</h1>
<p>Find me in app/views/members/create.html.erb</p>

app/views/members/destroy.html.erb
<h1>Members#destroy</h1>
<p>Find me in app/views/members/destroy.html.erb</p>

app/views/members/edit.html.erb
<%= render 'club/header' %>

<div id="main">
	<h1>Members#edit</h1>
	<p>Find me in app/views/members/edit.html.erb</p>
</div>

<%= render 'club/footer' %>

app/views/members/index.html.erb
<%= render 'club/header' %>

<div id="main">
	<h1>Liste des membres</h1>
	<p>Responsables seulement</p>
	<% members.index() %>
</div>

<%= render 'club/footer' %>

app/views/members/new.html.erb
<%= render 'club/header' %>

<div id="main">
	<h1>Members#new</h1>
	<p>Find me in app/views/members/new.html.erb</p>
</div>

<%= render 'club/footer' %>

app/views/members/show.html.erb
<%= render 'club/header' %>

<div id="main">
	<h1>Members#show</h1>
	<p>Find me in app/views/members/show.html.erb</p>
</div>

<%= render 'club/footer' %>

app/views/members/update.html.erb
<h1>Members#update</h1>
<p>Find me in app/views/members/update.html.erb</p>